export const FETCH_NOTIFICATION = "FETCH_NOTIFICATION"
export const FETCH_NOTIFICATION_FULFILLED = "FETCH_NOTIFICATION_FULFILLED"
export const FETCH_NOTIFICATION_CANCELLED = "FETCH_NOTIFICATION_CANCELLED"
export const FETCH_NOTIFICATION_ERROR = "FETCH_NOTIFICATION_ERROR"