export const FETCH_RTHK_NEWS = "FETCH_RTHK_NEWS"
export const FETCH_RTHK_NEWS_FULFILLED = "FETCH_RTHK_NEWS_FULFILLED"
export const FETCH_RTHK_NEWS_CANCELLED = "FETCH_RTHK_NEWS_CANCELLED"
export const FETCH_RTHK_NEWS_ERROR = "FETCH_RTHK_NEWS_ERROR"