export const LOAD_SETTINGS = "LOAD_SETTINGS"
export const LOAD_SETTINGS_FULFILLED = "LOAD_SETTINGS_FULFILLED";
export const LOAD_SETTINGS_CANCELLED = "LOAD_SETTINGS_CANCELLED";
export const LOAD_SETTINGS_ERROR = "LOAD_SETTINGS_ERROR";

export const UPDATE_SETTINGS = "UPDATE_SETTINGS"
export const UPDATE_SETTINGS_FULFILLED = "UPDATE_SETTINGS_FULFILLED"
export const UPDATE_SETTINGS_CANCELLED = "UPDATE_SETTINGS_CANCELLED"
export const UPDATE_SETTINGS_ERROR = "UPDATE_SETTINGS_ERROR"