export const FETCH_WEATHER_WARNING = "FETCH_WEATHER_WARNING"
export const FETCH_WEATHER_WARNING_FULFILLED = "FETCH_WEATHER_WARNING_FULFILLED"
export const FETCH_WEATHER_WARNING_CANCELLED = "FETCH_WEATHER_WARNING_CANCELLED"
export const FETCH_WEATHER_WARNING_ERROR = "FETCH_WEATHER_WARNING_ERROR"